"""fix name updated_at

Revision ID: 1c1d064baeb7
Revises: bd89bae9b8e4
Create Date: 2024-06-27 22:23:52.315181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1d064baeb7'
down_revision: Union[str, None] = 'bd89bae9b8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('Users', 'updcreated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('updcreated_at', sa.DATETIME(), nullable=False))
    op.drop_column('Users', 'updated_at')
    # ### end Alembic commands ###
