"""include updated_at field

Revision ID: b777c7b49412
Revises: d940f23bbb95
Create Date: 2024-06-27 23:16:11.195100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b777c7b49412'
down_revision: Union[str, None] = 'd940f23bbb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'updated_at')
    # ### end Alembic commands ###
